import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/shared/navbar";
import ReactQueryProvider from "@/config/queryClient";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <ReactQueryProvider>

        <Navbar />
        {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
